version: "3.3"
services:
  go-app:
    build:
      context: go-app
      dockerfile: dockerfile
    ports:
      - 5000:5000
    env_file:
      - .env
    container_name: go-apps
    networks:
      - gomicronetwork
  
  db-mysql:
    container_name: db-mysql
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD={DB_PASSWORD}
      - MYSQL_DATABASE={DB_NAME}
    networks:
      - gomicronetwork
  

